export const notificationsData = [
    {
      profileImg: "https://placehold.co/40x40",
      name: "official_d.eep_mehra",
      action: "Follow requests",
      additionalInfo: "official_d.eep_mehra + 7 others",
      type: "request",
      time: "",
    },
    {
      profileImg: "https://placehold.co/40x40",
      name: "dvinderx13",
      action: "liked your comment",
      additionalInfo: "🔥🔥",
      time: "3d",
      type: "comment",
    },
    {
      profileImg: "https://placehold.co/40x40",
      name: "lifts_raj_s92.0",
      action: "liked your story",
      additionalInfo: "lifts_raj_s92.0 and others",
      time: "3d",
      type: "story",
    },
    {
      profileImg: "https://placehold.co/40x40",
      name: "jashan_1224",
      action: "started following you",
      time: "1w",
      type: "follow",
    },
    {
      profileImg: "https://placehold.co/40x40",
      name: "official_d.eep_mehra",
      action: "requested to follow you",
      time: "2w",
      type: "request",
    },
  ];